// Generated by scripts/generate-command-types.mjs from #[tauri::command] signatures.
// Run `yarn generate:commands` after adding or changing one.
import { invoke } from '@tauri-apps/api/core';

type Commands = {
  analyze_track: { args: { path: string }; returns: unknown };
  clear_loop_region: { args: { deck: string }; returns: void };
  confirm_quit: { args: Record<string, never>; returns: void };
  discard_recording: { args: { path: string }; returns: void };
  eject_track: { args: { deck: string }; returns: void };
  files_info: { args: { paths: string[] }; returns: (number | null)[] };
  get_deck_levels: { args: Record<string, never>; returns: Record<string, [number, number]> };
  get_master_level: { args: Record<string, never>; returns: [number, number] };
  get_spectral_waveform_region: {
    args: { deck: string; startSec: number; endSec: number; numPoints: number };
    returns: unknown;
  };
  get_track_amplitude_region: {
    args: { path: string; startSec: number; endSec: number; numPoints: number };
    returns: number[];
  };
  get_track_amplitude_waveform: { args: { path: string; numPoints: number }; returns: unknown };
  list_audio_devices: { args: Record<string, never>; returns: unknown[] };
  list_midi_devices: { args: Record<string, never>; returns: unknown[] };
  load_track: {
    args: { deck: string; path: string; analyze: boolean; beatOffsetSec: number };
    returns: unknown;
  };
  open_session_dialog: { args: Record<string, never>; returns: unknown | null };
  pick_save_path: { args: { format: string; baseName: string }; returns: string | null };
  play: { args: { deck: string; fromSec: number | null }; returns: void };
  preload_session: { args: { path: string }; returns: void };
  press_cue: { args: { deck: string }; returns: unknown };
  read_file: { args: { path: string }; returns: string };
  read_track_tags: { args: { path: string }; returns: unknown };
  release_cue: { args: { deck: string }; returns: unknown };
  render_session_to_file: {
    args: { sessionPath: string; outputPath: string; useFlac: boolean; writeCue: boolean };
    returns: void;
  };
  save_bms_only: { args: { src: string; dest: string }; returns: void };
  save_recording: {
    args: { src: string; dest: string; writeBms: boolean; writeCue: boolean };
    returns: void;
  };
  save_session: { args: { path: string; content: string }; returns: void };
  scan_folder: { args: { path: string }; returns: string[] };
  seek: { args: { deck: string; sec: number }; returns: unknown };
  set_app_mode: { args: { mode: unknown }; returns: void };
  set_beat_grid: { args: { deck: string; bpm: number; beatOffsetSec: number }; returns: void };
  set_bpm_range: { args: { min: number; max: number }; returns: void };
  set_buffer_size: { args: { frames: number }; returns: void };
  set_cue_active: { args: { deck: string; active: boolean }; returns: void };
  set_cue_and_stop: { args: { deck: string }; returns: unknown };
  set_cue_device: { args: { deviceId: string; channelOffset: number }; returns: void };
  set_cue_mix: { args: { mix: number }; returns: void };
  set_deck_muted: { args: { deck: string; muted: boolean }; returns: void };
  set_deck_param: {
    args: { deck: string; slot: string; param: string; value: number };
    returns: void;
  };
  set_fader_curve: { args: { curve: unknown }; returns: void };
  set_jog_rotation_speed: { args: { speed: unknown }; returns: void };
  set_limiter_enabled: { args: { enabled: boolean }; returns: void };
  set_loop_active: { args: { deck: string; active: boolean }; returns: unknown };
  set_loop_in: { args: { deck: string }; returns: unknown };
  set_loop_out: { args: { deck: string }; returns: unknown | null };
  set_loop_region: { args: { deck: string; startSec: number; endSec: number }; returns: void };
  set_main_device: { args: { deviceId: string; channelOffset: number }; returns: void };
  set_master_gain: { args: { gain: number }; returns: void };
  set_midi_device_deck: { args: { port: string; deck: string | null }; returns: void };
  set_midi_monitor: { args: { enabled: boolean }; returns: void };
  set_nudge: { args: { deck: string; percent: number }; returns: unknown };
  set_pitch_range: { args: { percent: number }; returns: void };
  set_playback_rate: { args: { deck: string; rate: number }; returns: void };
  set_quantize: { args: { deck: string; quantize: boolean }; returns: void };
  set_reloop: { args: { deck: string }; returns: unknown };
  set_xfader_assign: { args: { deck: string; assign: string }; returns: void };
  set_xfader_position: { args: { position: number }; returns: void };
  start_recording: {
    args: { bitDepth: number; useFlac: boolean; recordSession: boolean };
    returns: void;
  };
  start_session_playback: { args: { path: string; fromMs: number }; returns: void };
  stop: { args: { deck: string }; returns: void };
  stop_at_cue: { args: { deck: string }; returns: unknown };
  stop_recording: { args: Record<string, never>; returns: string };
  stop_session_playback: { args: Record<string, never>; returns: void };
  toggle_play: { args: { deck: string }; returns: unknown };
  unload_session: { args: { path: string }; returns: void };
  update_session_events: { args: { path: string; eventsJson: string }; returns: void };
};

export type CommandName = keyof Commands;

export function call<Name extends CommandName>(
  command: Name,
  ...args: Commands[Name]['args'] extends Record<string, never> ? [] : [Commands[Name]['args']]
): Promise<Commands[Name]['returns']> {
  return invoke(command, args[0]);
}
